drop schema studentska_zadruga;
create schema studentska_zadruga;
use studentska_zadruga;
CREATE TABLE ADMINISTRATIVNI_RADNIK
(
	A_JMB CHAR(13) NOT NULL
);



ALTER TABLE ADMINISTRATIVNI_RADNIK
ADD PRIMARY KEY (A_JMB);



CREATE TABLE BANKA
(
	BankaId              VARCHAR(20) NOT NULL,
	BrojTelefona         INTEGER NOT NULL,
	Adresa               VARCHAR(20) NOT NULL,
	ZIPkod               INTEGER NOT NULL
);



ALTER TABLE BANKA
ADD PRIMARY KEY (BankaId);



CREATE TABLE CLAN
(
	C_JMB                CHAR(13) NOT NULL,
	Ime                  VARCHAR(50) NOT NULL,
	Prezime              VARCHAR(50) NOT NULL,
	Adresa               VARCHAR(50) NOT NULL,
	ZIPkod               INTEGER NOT NULL,
	BrojClanskeKarte     INTEGER NOT NULL,
	BrojLK               VARCHAR(20) NULL,
	DatumIstekaClanskeKarte DATE NULL,
	A_JMB                CHAR(13) NOT NULL,
    Aktivan				 BOOLEAN DEFAULT TRUE
);



ALTER TABLE CLAN
ADD PRIMARY KEY (C_JMB);



CREATE TABLE CLAN_POSAO
(
	BrojRadnihSati       FLOAT NULL,
    Zaradjeno		 	 FLOAT NULL,
	C_JMB                VARCHAR(13)  NULL,
	PosaoId              INTEGER NULL,
    Datum				 DATE NULL
);



ALTER TABLE CLAN_POSAO
ADD PRIMARY KEY (C_JMB,PosaoId);



CREATE TABLE FIZICKO_LICE
(
	PoslodavacId         INTEGER NOT NULL,
	Ime                  VARCHAR(50) NOT NULL,
	Prezime              VARCHAR(50) NOT NULL,
	BrojLK       		 VARCHAR(20) NULL,
    Aktivan				 BOOLEAN DEFAULT TRUE
);



ALTER TABLE FIZICKO_LICE
ADD PRIMARY KEY (PoslodavacId);



CREATE TABLE IZVJESTAJ_B
(
	IzvjestajId          INTEGER NOT NULL,
	Datum                DATE NULL,
	BankaId              VARCHAR(20) NOT NULL,
	A_JMB                CHAR(13) NULL
);



ALTER TABLE IZVJESTAJ_B
ADD PRIMARY KEY (IzvjestajId);



CREATE TABLE IZVJESTAJ_P
(
	IzvjestajId          INTEGER NOT NULL,
	Datum                DATE NULL,
	Naknada              FLOAT NULL,
	PoslodavacId         INTEGER NULL,
	A_JMB                CHAR(13) NULL
);



ALTER TABLE IZVJESTAJ_P
ADD PRIMARY KEY (IzvjestajId);



CREATE TABLE KOMPANIJA
(
	PoslodavacId         INTEGER NOT NULL,
	Naziv                VARCHAR(50) NOT NULL,
	Adresa               VARCHAR(50) NOT NULL,
	JIB                  CHAR(13) NOT NULL,
    Aktivan 			 BOOLEAN DEFAULT TRUE
);



ALTER TABLE KOMPANIJA
ADD PRIMARY KEY (PoslodavacId);



CREATE TABLE MJESTO
(
	ZIPkod               INTEGER NOT NULL,
	Naziv                VARCHAR(20) NULL
);



ALTER TABLE MJESTO
ADD PRIMARY KEY (ZIPkod);



CREATE TABLE PARTNER
(
	PartnerId            INTEGER NOT NULL,
	Naziv                VARCHAR(50)  NULL,
	JIB                  CHAR(13) NULL
);



ALTER TABLE PARTNER
ADD PRIMARY KEY (PartnerId);



CREATE TABLE PARTNER_POSAO_AR
(
	PosaoId              INTEGER  NULL,
	PartnerId            INTEGER  NULL,
	A_JMB                CHAR(13) NULL
);



ALTER TABLE PARTNER_POSAO_AR
ADD PRIMARY KEY (PosaoId,PartnerId);



CREATE TABLE POSAO
(
	PosaoId         	 INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	CijenaPoSatu         DECIMAL(10, 2) NULL,
	OpisPosla            VARCHAR(100) NULL,
	Zavrsen              boolean NULL default false ,
	BrojPotrebnihRadnika INTEGER NULL,
	A_JMB                CHAR(13) NOT NULL,
	PoslodavacId         INTEGER NOT NULL
);





CREATE TABLE POSLODAVAC
(
	PoslodavacId         INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	ZIPkod               INTEGER NOT NULL
);





CREATE TABLE RACUN
(
	BrojZiroracuna       CHAR(18) NOT NULL,
	BankaId              VARCHAR(20) NOT NULL
);



ALTER TABLE RACUN
ADD PRIMARY KEY (BrojZiroracuna);



CREATE TABLE RADNIK
(
	A_JMB                CHAR(13) NOT NULL
);



ALTER TABLE RADNIK
ADD PRIMARY KEY (A_JMB);



CREATE TABLE TELEFON_CLAN
(
	BrojTelefona         CHAR(18) NOT NULL,
	C_JMB                VARCHAR(20) NOT NULL
);



ALTER TABLE TELEFON_CLAN
ADD PRIMARY KEY (BrojTelefona,C_JMB);



CREATE TABLE TELEFON_PARTNER
(
	BrojTelefona         FLOAT NULL,
	PartnerId            INTEGER NOT NULL
);



ALTER TABLE TELEFON_PARTNER
ADD PRIMARY KEY (PartnerId);



CREATE TABLE TELEFON_POSLODAVAC
(
	BrojTelefona         CHAR(18) NOT NULL,
	PoslodavacId         INTEGER NOT NULL
);



ALTER TABLE TELEFON_POSLODAVAC
ADD PRIMARY KEY (BrojTelefona,PoslodavacId);



CREATE TABLE TELEFON_ZAPOSLENI
(
	BrojTelefona         INTEGER NOT NULL,
	A_JMB                CHAR(13) NOT NULL
);



ALTER TABLE TELEFON_ZAPOSLENI
ADD PRIMARY KEY (BrojTelefona,A_JMB);



CREATE TABLE UGOVOR
(
	UgovorId             INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	DatumPotpisivanja    DATE NULL,
	Uslovi               TEXT NULL,
	Naknada              DECIMAL (10, 2) NULL,
	A_JMB                CHAR(13) NOT NULL,
	PoslodavacId         INTEGER NOT NULL
);



CREATE TABLE ZAPOSLENI
(
	A_JMB                CHAR(13) NOT NULL,
	Ime                  VARCHAR(50) NOT NULL,
	Prezime              VARCHAR(50) NULL,
	KorisnickoIme        VARCHAR(20) NOT NULL,
	Lozinka              VARCHAR(64) NOT NULL
);



ALTER TABLE ZAPOSLENI
ADD PRIMARY KEY (A_JMB);



ALTER TABLE ADMINISTRATIVNI_RADNIK
ADD FOREIGN KEY (A_JMB) REFERENCES ZAPOSLENI(A_JMB)
		ON DELETE CASCADE;



ALTER TABLE BANKA
ADD FOREIGN KEY R_31 (ZIPkod) REFERENCES MJESTO (ZIPkod);



ALTER TABLE CLAN
ADD FOREIGN KEY R_32 (ZIPkod) REFERENCES MJESTO (ZIPkod);



ALTER TABLE CLAN
ADD FOREIGN KEY R_79 (A_JMB) REFERENCES ADMINISTRATIVNI_RADNIK (A_JMB);



ALTER TABLE CLAN_POSAO
ADD FOREIGN KEY R_65 (C_JMB) REFERENCES CLAN (C_JMB);



ALTER TABLE CLAN_POSAO
ADD FOREIGN KEY R_66 (PosaoId) REFERENCES POSAO (PosaoId);



ALTER TABLE FIZICKO_LICE
ADD FOREIGN KEY (PoslodavacId) REFERENCES POSLODAVAC(PoslodavacId)
		ON DELETE CASCADE;



ALTER TABLE IZVJESTAJ_B
ADD FOREIGN KEY obradjuje (BankaId) REFERENCES BANKA (BankaId);



ALTER TABLE IZVJESTAJ_B
ADD FOREIGN KEY R_74 (A_JMB) REFERENCES ADMINISTRATIVNI_RADNIK (A_JMB);



ALTER TABLE IZVJESTAJ_P
ADD FOREIGN KEY R_58 (PoslodavacId) REFERENCES POSLODAVAC (PoslodavacId);



ALTER TABLE IZVJESTAJ_P
ADD FOREIGN KEY R_75 (A_JMB) REFERENCES ADMINISTRATIVNI_RADNIK (A_JMB);



ALTER TABLE KOMPANIJA
ADD FOREIGN KEY (PoslodavacId) REFERENCES POSLODAVAC(PoslodavacId)
		ON DELETE CASCADE;



ALTER TABLE PARTNER_POSAO_AR
ADD FOREIGN KEY R_62 (PosaoId) REFERENCES POSAO (PosaoId);



ALTER TABLE PARTNER_POSAO_AR
ADD FOREIGN KEY R_63 (PartnerId) REFERENCES PARTNER (PartnerId);



ALTER TABLE PARTNER_POSAO_AR
ADD FOREIGN KEY upravlja (A_JMB) REFERENCES ADMINISTRATIVNI_RADNIK (A_JMB);



ALTER TABLE POSAO
ADD FOREIGN KEY nudi (PoslodavacId) REFERENCES POSLODAVAC (PoslodavacId);



ALTER TABLE POSAO
ADD FOREIGN KEY R_78 (A_JMB) REFERENCES ADMINISTRATIVNI_RADNIK (A_JMB);



ALTER TABLE POSLODAVAC
ADD FOREIGN KEY R_33 (ZIPkod) REFERENCES MJESTO (ZIPkod);



ALTER TABLE RACUN
ADD FOREIGN KEY R_4 (BankaId) REFERENCES BANKA (BankaId);



ALTER TABLE RADNIK
ADD FOREIGN KEY (A_JMB) REFERENCES ZAPOSLENI(A_JMB)
		ON DELETE CASCADE;



ALTER TABLE TELEFON_CLAN
ADD FOREIGN KEY R_56 (C_JMB) REFERENCES CLAN (C_JMB);



ALTER TABLE TELEFON_PARTNER
ADD FOREIGN KEY R_64 (PartnerId) REFERENCES PARTNER (PartnerId);



ALTER TABLE TELEFON_POSLODAVAC
ADD FOREIGN KEY R_59 (PoslodavacId) REFERENCES POSLODAVAC (PoslodavacId);



ALTER TABLE TELEFON_ZAPOSLENI
ADD FOREIGN KEY R_72 (A_JMB) REFERENCES ZAPOSLENI (A_JMB);



ALTER TABLE UGOVOR
ADD FOREIGN KEY R_49 (PoslodavacId) REFERENCES POSLODAVAC (PoslodavacId);



ALTER TABLE UGOVOR
ADD FOREIGN KEY R_77 (A_JMB) REFERENCES ADMINISTRATIVNI_RADNIK (A_JMB);

